variable "vpc_name" {}
variable "subnet_name" {}
variable "region" {}
variable "project_id" {}
variable "account_id_kubernetes" {}
variable "initial_node_count" {}
variable "node_zones" {}
variable "master_ipv4_cidr_block" {}
variable "authorized_ipv4_cidr_block" {}
variable "pods_ipv4_cidr_block" {}
variable "services_ipv4_cidr_block" {}
