region             = ""
dev_folder_id      = ""
folder_name        = ""
project_name       = ""
project_id         = ""
org_id             = ""
billing_account_id = ""
api_names          = ["xyz", "xyz"]
vpc_name           = ""
subnet_cidr        = ["xyz", "xyz"]
subnet_name        = ""
vm_name            = ""
machine_type       = ""
zone               = ""
